interface RootHeadProps {}

function RootHead({}: RootHeadProps) {
  return (
    <>
      <title>Landjäger</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </>
  );
}

export default RootHead;
